# Generated by Django 2.0.2 on 2018-03-05 12:35

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command('loaddata', 'menu/fixtures.json')


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
    ]
