# Generated by Django 2.0.2 on 2018-03-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180305_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='toppings_through',
            new_name='toppings',
        ),
    ]
